spring:
  profiles:
    # Specify profiles corresponding to featbee features
    # active: featbee-telegram,featbee-captcha
    active: default
  datasource:
    url: "jdbc:postgresql://localhost/featbee"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: "classpath:changelog.yml"

# Telegram related settings
# Will be in use only if featbee-telegram is specified in active profiles
featbee:
  # Allowed domains (CORS), remove or set to * to allow any
  domains: "*"
  captcha:
    secret: "_please_fill_in_recaptcha_secret_in_application_properties_"
    sitekey: "_please_fill_in_recaptcha_sitekey_in_application_properties_"
  telegram:
    token: "_please_fill_in_telegram_token_in_application_properties_"
    receiver: "_please_fill_in_receiver_in_application_properties_"

    changedMessage: |
      IP: _{ip}_
      
      Visibility:
      _{oldVisibility}_ -> _{newVisibility}_
      
      Score:
      _{oldScore}_ -> **{newScore}**
      
      Old comment:
      `{oldContent}`
      
      New comment:
      `{newContent}`
      ­

    producedMessage: |
      IP: {ip}
      
      Visibility: {visibility}
      Score: **{score}**
      
      Comment:
      ```{content}```
      ­